version: '3.7'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE=Asia/Kolkata
    volumes:
      - ./.n8n:/home/node/.n8n 